const colorCSS = document.querySelector('skills').backgroundColor = '#264de4'
const colorHTML = document.querySelector('skills').backgroundColor = '#e44d26'
const colorJS = document.querySelector('skills').backgroundColor = '#f4dd40'
const colorMongoDB = document.querySelector('skills').backgroundColor = '#00684a'
const colorNodeJS = document.querySelector('skills').backgroundColor = '#333333'
const colorPostgreSQL = document.querySelector('skills').backgroundColor = '#336791'
const colorReact = document.querySelector('skills').backgroundColor = '#282c34'